name: mumble_build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clone mumble
      run: git clone https://github.com/mumble-voip/mumble
    - name: Setup Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.2.*'
        target: 'desktop'
    - name: Build Qt
      run: |
        cd mumble
        cmake .
        make .
    - name: Upload release
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: "./*"
