name: mumble_build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.18
    - name: Check Python Version
      run: python -V
    - name: Download mumble 
      run: |
        wget https://github.com/mumble-voip/mumble/releases/download/v1.5.634/mumble-1.5.634.tar.gz
        tar -xzvf mumble-1.5.634.tar.gz
    - name: setup env
      run: |  
        #sudo apt-get install protobuf-compiler
        #sudo apt-get install openssl libssl-dev
        sudo apt install build-essential cmake pkg-config qt5-qmake qtbase5-dev qttools5-dev qttools5-dev-tools libqt5svg5-dev libboost-dev libssl-dev libprotobuf-dev protobuf-compiler libprotoc-dev libcap-dev libxi-dev libasound2-dev libogg-dev libsndfile1-dev \libopus-dev libspeechd-dev libavahi-compat-libdnssd-dev libxcb-xinerama0 libzeroc-ice-dev libpoco-dev g++-multilib
        #git clone -b main https://github.com/pocoproject/poco.git
        #cd poco
        #mkdir cmake-build
        #cd cmake-build
        #cmake ..
        #cmake --build . --config Release
        #sudo cmake --build . --target install
        #vcpkg install POCO
    #- name: Setup Qt
    #  uses: jurplel/install-qt-action@v3
    #  with:
    #    version: '5.15.*'
    #    target: 'desktop'
    - name: Build Qt
      run: |
        cd mumble-1.5.634
        mkdir build
        cd build
        cmake -Dclient=OFF ..
        make -j $(nproc)
    - name: Upload release
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: "./mumble*/build/*"
